### ISSUE TITLE
prevOutput shouldn't be in output calculation

### ISSUE THREAD

**Issue by redbaron** [gbmhunter/Pid-C#12]
``` C
///Compute PID Output
pidData->output = pidData->prevOutput + pidData->zKp*pidData->error + pidData->iTerm + pidData->dTerm;
```

Why do you use prevOutput to calculate output? According to wikipedia article it shouldn't be there at all

**Comment by gbmhunter** [comment]
You use it if you are doing accumulating PID (e.g. velocity control), rather than pure proportional (e.g. positional control). See http://cladlab.com/programming/general/pid-control#different-types-of-pid-control on my website for more info on this.

**Comment by gbmhunter** [comment]
I really need to explain this better, and provide an option for setting the PID in either mode. Will do! I have a PID library written in C++ also (C3id) which is more "maintained" and has this option. Do you use C++ at all for embedded stuff (assuming you do embedded stuff in the first place)?

**Comment by redbaron** [comment]
I think it's time to close it :)

**Comment by gbmhunter** [comment]
Fair enough :-)
